### ISSUE TITLE
Typo in ccip.TokenPool docs

### ISSUE THREAD

**Issue by miguelmtzinf** [smartcontractkit/ccip#341]
https://github.com/smartcontractkit/ccip/blob/bc3fba39c6c8ca61a072fe49c5df697ecc5a3a3f/contracts/src/v0.8/ccip/pools/TokenPool.sol#L63-L71

Are docs of L69 correct? Using `outbound` and `inbound` terms for the same thing. These terms are only used here for the first time and are a bit misleading given that it depends on the pov.

Btw, there is a tiny typo in L65 in the word "degress"

**Comment by jarnaud** [comment]
I think there is no typo here, using "degrees" as plurar of "degree" it seems.

**Comment by miguelmtzinf** [comment]
oh, my local workspace seems a bit outdated @jarnaud 

Still, the terms used are a bit confusing.

**Comment by RensR** [comment]
From the POV of the pool, these comments are correct
