### ISSUE TITLE
[DEVEL] <How to send other tokens using ccip>

### ISSUE THREAD

**Issue by kamalbuilds** [smartcontractkit/ccip#435]
**Description**

I want to send an ERC-20 token like USDC , DAI etc , but i am getting Token not supported error.

How can I add any token in the supported list of tokens ?

**Your Environment**
[replace this line with basic information about your environment, such as your operating system and the versions of any relevant tools you are using (e.g. Go, Docker)]

**Basic Information**
[replace this line with basic information about the issue you are experiencing, including but not limited to the names of the files you are working with and any relevant error messages]

**Steps to Reproduce**
[replace this line with detailed steps to reproduce the issue you are experiencing]

**Additional Information**
[replace this line with any additional information you would like to provide, such as screenshots illustrating the issue]

**Comment by RensR** [comment]
Please check the [docs](https://docs.chain.link/ccip/supported-networks) for all supported tokens. USDC should be enabled on most chains that Circle supports CCTP. Do make sure you use the 1.2 lanes, as the deprecated 1.0 lanes do not support it.


To list additional tokens, please reach out on e.g. Discord for more information
