### ISSUE TITLE
[DEVEL] Add supplementary check in MockCCIPRouter

### ISSUE THREAD

**Issue by rya-sge** [smartcontractkit/ccip#755]
Hello,
Congratulations for all your work ! The code is very clear to understand.
A quick remark:

**Description**
The function [ccipSend](https://github.com/smartcontractkit/ccip/blob/a75966095e93a97e0ed181cda6fabaac137e0ef1/contracts/src/v0.8/ccip/test/mocks/MockRouter.sol#L71)  in [MockCCIPRouter ](https://github.com/smartcontractkit/ccip/blob/a75966095e93a97e0ed181cda6fabaac137e0ef1/contracts/src/v0.8/ccip/test/mocks/MockRouter.sol) doesn't check if:
-  `msg.value` is enough to pay the fees in the case of using native tokens.
- if `msg.value == 0`  if non native tokens are used

I think it could be a great improvement for automatic tests to add these checks in order to be closer to the true behavior of the router.

**Basic Information**
Example:

>  function ccipSend(
    uint64 destinationChainSelector,
    Client.EVM2AnyMessage calldata message
  ) external payable returns (bytes32) {
    uint256 feeTokenAmount = getFee(destinationChainSelector, message);
    if (message.feeToken == address(0)) {
        if (msg.value < feeTokenAmount) revert InsufficientFeeTokenAmount();
    } else{
        if (msg.value > 0) revert InvalidMsgValue();
    }

**Comment by jhweintraub** [comment]
Thank you for the request. You can track progress on the issue at the following PR

https://github.com/smartcontractkit/ccip/pull/896

**Comment by rya-sge** [comment]
Great, thank you very much !

**Comment by RensR** [comment]
https://github.com/smartcontractkit/ccip/pull/896
